### ISSUE TITLE
Does not work behind a corporate proxy

### ISSUE THREAD

**Issue by sunilkum84** [neatc0der/mkdocs-markmap#20]
Thanks for this Excellent Plugin. Its very helpful for me in preparing Mindmaps
one thing where I face issue is when I am behind a proxy, the script hangs when trying to download the dependent javascripts.
I some how tried to make it work by making the below changes. Do you think this change make sense or if you can suggest some better ways to overcome this problem.
![image](https://user-images.githubusercontent.com/36337706/132993301-09b2e66f-a85c-42b3-83b9-6fb1a1b2eaba.png)

**Comment by neatc0der** [comment]
Thanks for reporting the issue. Unfortunately, I'm unable to reproduce the error or verify the fix. But I do see the advantage in using `requests`. Thus, please see #21 and verify if possible.

I'm currently waiting for further analysis on #19 to conclude `v2.1.1`.

**Comment by neatc0der** [comment]
Thanks! That qualifies for a release.
